### ISSUE TITLE
WhatsApp like delete animation

### ISSUE THREAD

**Issue by shainsingh89** [3llomi/RecordView#13]
I have added the Whatsapp like delete mic animation.

Create pull request for same

**Comment by 3llomi** [comment]
Thanks man .
I tried to build it to see the new Animation and it's fantastic . I was planning to add the same animation in future release. So great job.
However i think it need a little modifications:
1-the Alpha animation for the ```smallBlinkingMic```
Must be  removed when starts the animation, because it may still animating while performing the the rotation and translation animations
2-the ```basketAnimation``` time is too long when it's animating down.

Let me what you think.

**Comment by 3llomi** [comment]
@shainsingh89 OK, i will accept PR now and i will modify it with a new update later.
Thanks for this Beautiful Animation.
