### ISSUE TITLE
if the phone's system font size is too large, the audio recording will be canceled as soon as it starts

### ISSUE THREAD

**Issue by erengms** [3llomi/RecordView#77]
When the phone system font is too large, the sound recording will be canceled because the view starts directly aligned to the left.

**Comment by 3llomi** [comment]
Hey @erengms ,
you can increase the bounds by calling 
`recordView.setCancelBounds(12);//dp`

**Comment by erengms** [comment]
I did but it doesn't work. For now, I've set -40dp to make it slide on top of the clock.

**Comment by LizZerrG** [comment]
I'm having the same problem. I've tried setting `recordView.cancelBounds = 12f` (and some other values), but it doesn't seem to solve anything. It does work when I set the `SlideToCancelText` to something short, but that is just a workaround. 

How would this work in version 3.1.3? Isn't there a better solution to make this work for people with not-so-good-eyesight?

Also, it looks like it was improved in some newer version, but it doesn't work for all font sizes (yet?). When you've set the fontsize to the biggest option (option 8 on Samsung S22, Android 13) the recordView works, but it doesn't work for option 5 to 7. (Settings > Display > Font size and style > Font Size, then on Samsung you have 8 font size options to choose from).

**Comment by 3llomi** [comment]
Hi @LizZerrG ,

I tried to set a maxWidth to SlideToCancelText and it seems to be working since the text will have multilines.

![image](https://github.com/3llomi/RecordView/assets/8546946/99177c4f-51a1-4f92-8d12-4a3d23aeb3be)

So I'm thinking of exposing a 'setMaxWidth' for slideToCancel.

Let me know if this fixes your issue so I can publish it to 3.1.4
